apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.example.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - ollama-deployment.yaml
  - ollama-service.yaml
